# Generated by Django 3.2.12 on 2022-06-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='volume',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Volume'),
        ),
    ]
